### PR TITLE
Fix dropdown issues

### PR DESCRIPTION
**Pull request by Ommanimesh2**

### CODE REVIEW

**Comment by seanred360** [comment]
Nice job! Thanks for your help.

**Comment by seanred360** [comment]
> _ No description provided. _

I think we can refactor this code so that others can read it easier. Can we make 1 dropdown component and then just reuse it for all of the dropdowns? That way we do not have 4 different useState functions that are exactly the same thing.

Can we change these into 1 component?

```
 <div onClick={handleBookmark} className="faqs-section-items">
           <div  className="flex justify-between border-t-0 px-0 py-[20px] text-[15px] text-left">
              What is a bookmark?{" "}
             {faqBookmark ? <Icon  className="chevron" icon="akar-icons:chevron-up" /> : <Icon className="chevron" icon="akar-icons:chevron-down" />}
           </div>
          {faqBookmark ? <div className="hidden-text toggle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti delectus sit voluptatum dolor, rem sequi? Illum molestias obcaecati sequi at, recusandae ea dolorum fugiat quisquam.</div> : <div></div>}
         </div>
```

To something like this?

```
const faq = () => {
const [toggle, setToggle] = useState(false)

return (
<div onClick={setToggle}>Faq stuff here<div>
 )
}
```

If we do it this way we can remove all these duplicate useStates and then if we need to add 20 FAQS in the future it would only take a few minutes to add them.

```const handleBookmark=()=>{
      if(faqBookmark){
        setfaqBookmark(false)
      }
      else{
        setfaqBookmark(true)
      }
  }
  const handleChromiumReq=()=>{
      if(faqChromium){
        setfaqChromium(false)
      }
      else{
        setfaqChromium(true)
      }
  }
  const handleBrowserReq=()=>{
      if(faqBrowser){
        setfaqBrowser(false)
      }
      else{
        setfaqBrowser(true)
      }
  }
  const handleMobileReq=()=>{
      if(faqMobile){
        setfaqMobile(false)
      }
      else{
        setfaqMobile(true)
      }
  }
```

**Comment by Ommanimesh2** [comment]
Ok I'll work on that now. @seanred360.

**Comment by Ommanimesh2** [comment]
@seanred360 I've opened another pull request after refactoring the code. Do check it out

**Comment by Ommanimesh2** [comment]
@seanred360 I've opened another pull request after refactoring the code. Do check it out

**Pull request merged**
