### PR TITLE
Refactor the dropdown code

### PR DESCRIPTION
**Pull request by Ommanimesh2**

### CODE REVIEW

**Review by seanred360 — APPROVED** [review]
Great job! This is pretty much what I asked for. I would use props next time rather than hard coding an array of FAQs. We should avoid making the keys something generic like 1,2,3,4 because React will confuse these with other elements. The purpose of the key is to give a unique identifier to each element so React knows they are different elements.

**Comment by seanred360** [comment]
Here is my solution to the problem. 
```
const FaqSection = () => {
  return (
    <section>
      <h5>Frequently Asked Questions</h5>
      <p>
        Here are some of our FAQs. If you have any other questions you'd like
        answered please feel free to email us.
      </p>

      <div className="px-[24px] faq-container">
        <Faq
          question="What is a bookmark?"
          answer="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione repudiandae provident repellendus quasi. Hic."
        />
        <Faq
          question="How can I request a new browser?"
          answer="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione repudiandae provident repellendus quasi. Hic."
        />
        <Faq
          question="Is there a mobile app?"
          answer="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione repudiandae provident repellendus quasi. Hic."
        />
        <Faq
          question="What about other Chromium browsers?"
          answer="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione repudiandae provident repellendus quasi. Hic."
        />
      </div>

      <div className="flex">
        <button className="mx-auto mt-[48px] mb-[123px]">More Info</button>
      </div>
    </section>
  );
};
```
We can make a new component with props and avoid using loops and keys.
```
const Faq = ({ question, answer }) => {
  const [toggle, setToggle] = useState(false);
  return (
    <div className="faqs-section-items">
      <div
        onClick={() => setToggle(!toggle)}
        className="flex justify-between border-t-0 px-0 py-[20px] text-[15px] text-left"
      >
        {question}
        <Icon
          className="chevron"
          icon={`akar-icons:chevron-${toggle ? "up" : "down"}`}
        />
      </div>
      {toggle ? (
        <div className="text-[15px] font-thin leading-[25px] text-[grayDark] opacity-[0.5]">
          {answer}
        </div>
      ) : null}
    </div>
  );
};
```

**Comment by seanred360** [comment]
It is a good practice to make sure all elements are the same level of abstraction in a component because it is easier to read. Only if possible and it makes sense though.

This looks better

```
const FaqSection = () => {
  return (
    <section>
        <Faq />
        <Faq />
        <Faq />
        <Faq />
    </section>
  );
};
```
This looks worse. We do not need to see the implementation details of the Faq component in the section to understand it.
```
<div className="faqs-section-items">
      <div
        onClick={() => setToggle(!toggle)}
        className="flex justify-between border-t-0 px-0 py-[20px] text-[15px] text-left"
      >
        {question}
        <Icon
          className="chevron"
          icon={`akar-icons:chevron-${toggle ? "up" : "down"}`}
        />
      </div>

<div
        onClick={() => setToggle(!toggle)}
        className="flex justify-between border-t-0 px-0 py-[20px] text-[15px] text-left"
      >
        {question}
        <Icon
          className="chevron"
          icon={`akar-icons:chevron-${toggle ? "up" : "down"}`}
        />
      </div>

<div
        onClick={() => setToggle(!toggle)}
        className="flex justify-between border-t-0 px-0 py-[20px] text-[15px] text-left"
      >
        {question}
        <Icon
          className="chevron"
          icon={`akar-icons:chevron-${toggle ? "up" : "down"}`}
        />
      </div>

<div
        onClick={() => setToggle(!toggle)}
        className="flex justify-between border-t-0 px-0 py-[20px] text-[15px] text-left"
      >
        {question}
        <Icon
          className="chevron"
          icon={`akar-icons:chevron-${toggle ? "up" : "down"}`}
        />
      </div>
    </div>

```

**Comment by Ommanimesh2** [comment]
Thank you for the thorough review. Learnt a lot today.
Will keep this in mind in the opensource journey 😁

**Pull request merged**
